<<<<<<< HEAD
title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
theme: jekyll-theme-slate
layout: post
title: Blogging Like a Hacker
>>>>>>> 62570eecdc85d7b1efa4d9ecfbe92e4c743f1efc
